const SHEET_NAME = 'items';
const RECURRENT_SHEET_NAME = 'recurrents';
const TRANSFER_SHEET_NAME = 'transfers';
const SHARED_SPENDING_SHEET_NAME = 'shared_spending';
const SETTINGS_SHEET_NAME = 'settings';
const TIMEZONE = 'Asia/Tokyo';
const DATE_FORMAT = 'yyyy-MM-dd';

const TYPE_INCOME = 'INCOME';
const TYPE_SHARED_SHOULD_PAY_BUT_PERSONAL_PAID = 'SHARED_SHOULD_PAY_BUT_PERSONAL_PAID';
const TYPE_PERSONAL_SHOULD_PAY_BUT_SHARED_PAID = 'PERSONAL_SHOULD_PAY_BUT_SHARED_PAID';
const TYPE_POCKET_MONEY = 'POCKET_MONEY';
const ALLOWED_TYPES = [
  TYPE_INCOME,
  TYPE_SHARED_SHOULD_PAY_BUT_PERSONAL_PAID,
  TYPE_PERSONAL_SHOULD_PAY_BUT_SHARED_PAID,
  TYPE_POCKET_MONEY,
];
